"""What to do about it.

Every recommendation here is derived from the network and the current readings
by ordinary arithmetic. None is generated by a language model, and none asserts
a cause: the data can say that three approaches to Darjeeling More are all slow
and that one officer standing there covers all three. It cannot say why they
are slow, and it does not guess.

Each recommendation carries the evidence it rests on and the thing it cannot
know, because a suggestion an officer cannot audit is a suggestion they will
stop reading.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

from packages.network.model import Network

# A junction is worth posting at when this many of its approaches are degraded.
CONVERGENCE_MIN = 2

# An alternative is only worth naming if it is genuinely better.
DIVERSION_MARGIN = 0.20      # 20% faster than the congested route
DIVERSION_MAX_EXTRA_M = 2500  # and not a wild detour


@dataclass
class Recommendation:
    kind: str                  # POST | DIVERT | ESCALATE | WATCH | STAND_DOWN
    urgency: str               # NOW | THIS_SHIFT | ADVISORY
    headline: str
    detail: str
    because: list[str]         # the evidence, in plain sentences
    cannot_know: str
    junctions: list[str] = field(default_factory=list)
    corridors: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "kind": self.kind,
            "urgency": self.urgency,
            "headline": self.headline,
            "detail": self.detail,
            "because": self.because,
            "cannot_know": self.cannot_know,
            "junctions": self.junctions,
            "corridors": self.corridors,
        }


def _degraded(board_corridors: list[dict]) -> list[dict]:
    return [c for c in board_corridors if c.get("band") in ("ELEVATED", "HIGH", "SEVERE")]


def recommend(network: Network, board: dict, now: datetime) -> list[Recommendation]:
    corridors = board.get("corridors", [])
    incidents = board.get("incidents", [])
    degraded = _degraded(corridors)
    by_id = {c["corridor_id"]: c for c in corridors}
    out: list[Recommendation] = []

    # ── 1. Convergence: several approaches to one junction, all degraded ────
    # This is the recommendation that pays for the whole engine. Three separate
    # corridor alerts look like three problems and invite three deployments;
    # one officer at the junction they share covers all of them.
    inbound: dict[str, list[dict]] = {}
    for c in degraded:
        corridor = network.corridor(c["corridor_id"])
        if corridor is None:
            continue
        inbound.setdefault(corridor.to_junction, []).append(c)

    for junction_id, approaches in sorted(
        inbound.items(), key=lambda kv: -len(kv[1])
    ):
        if len(approaches) < CONVERGENCE_MIN:
            continue
        junction = network.junction(junction_id)
        if junction is None:
            continue
        worst = max(approaches, key=lambda c: c.get("index") or 0)
        total_excess = sum(c.get("excess_minutes") or 0 for c in approaches)

        out.append(
            Recommendation(
                kind="POST",
                urgency="NOW" if len(approaches) >= 3 else "THIS_SHIFT",
                headline=f"Post an officer at {junction.name}",
                detail=(
                    f"{len(approaches)} of the {len(network.corridors_at(junction_id))} "
                    f"approaches to {junction.name} are slower than typical at the same time. "
                    f"One officer at the junction covers all of them; sending one to each road "
                    f"would be {len(approaches)} deployments for one problem."
                ),
                because=[
                    f"{c['name']} is {c['index']:.2f}× its typical time"
                    f"{f', {c['excess_minutes']:+.0f} min' if c.get('excess_minutes') is not None else ''}"
                    for c in sorted(approaches, key=lambda x: -(x.get("index") or 0))
                ]
                + [f"Together they account for about {total_excess:.0f} minutes of extra travel per journey set."]
                + (
                    [f"{junction.name} measured V/C {junction.vc_ratio:.2f} in the 2011 survey — "
                     f"{'already over capacity' if (junction.vc_ratio or 0) >= 1.0 else 'within its designed capacity'}."]
                    if junction.vc_ratio is not None else []
                ),
                cannot_know=(
                    "Whether the approaches share a cause. They share a destination, which is "
                    "why one post covers them, but the reason each is slow is not in this data."
                    + (" The pin for this junction is approximate." if junction.pin_is_approximate else "")
                ),
                junctions=[junction_id],
                corridors=[c["corridor_id"] for c in approaches],
            )
        )

    # ── 2. Diversion: is the reverse or a neighbour route materially better? ─
    for c in sorted(degraded, key=lambda x: -(x.get("index") or 0))[:4]:
        corridor = network.corridor(c["corridor_id"])
        if corridor is None:
            continue
        alternatives = []
        for other in network.corridors.values():
            if other.corridor_id == corridor.corridor_id:
                continue
            # A two-leg path from the same origin to the same destination.
            if other.from_junction != corridor.from_junction:
                continue
            leg2 = next(
                (
                    x for x in network.corridors.values()
                    if x.from_junction == other.to_junction
                    and x.to_junction == corridor.to_junction
                ),
                None,
            )
            if leg2 is None:
                continue
            a, b = by_id.get(other.corridor_id), by_id.get(leg2.corridor_id)
            if not a or not b:
                continue
            if a.get("duration_minutes") is None or b.get("duration_minutes") is None:
                continue
            direct = c.get("duration_minutes")
            via = a["duration_minutes"] + b["duration_minutes"]
            if direct is None or via >= direct * (1 - DIVERSION_MARGIN):
                continue
            if a.get("band") in ("HIGH", "SEVERE") or b.get("band") in ("HIGH", "SEVERE"):
                continue
            alternatives.append((via, other.to_junction, a, b))

        if not alternatives:
            continue
        via_minutes, through, leg_a, leg_b = min(alternatives, key=lambda x: x[0])
        through_junction = network.junction(through)
        saved = (c["duration_minutes"] or 0) - via_minutes

        out.append(
            Recommendation(
                kind="DIVERT",
                urgency="THIS_SHIFT",
                headline=(
                    f"{corridor.from_name} to {corridor.to_name} is quicker via "
                    f"{through_junction.name if through_junction else through}"
                ),
                detail=(
                    f"The direct route is running at {c['duration_minutes']:.0f} minutes against a "
                    f"typical {c['typical_minutes']:.0f}. Going via "
                    f"{through_junction.name if through_junction else through} currently measures "
                    f"{via_minutes:.0f} minutes — about {saved:.0f} minutes better right now."
                ),
                because=[
                    f"Direct: {c['name']} at {c['index']:.2f}× typical.",
                    f"Leg 1: {leg_a['name']} at {leg_a['duration_minutes']:.0f} min ({leg_a['band'].lower()}).",
                    f"Leg 2: {leg_b['name']} at {leg_b['duration_minutes']:.0f} min ({leg_b['band'].lower()}).",
                ],
                cannot_know=(
                    "Whether the alternative can absorb the traffic. This compares current "
                    "measurements on two routes; it does not model what happens if vehicles are "
                    "actually sent down the second one. Treat it as advice to a control room, not "
                    "as a signed-off diversion order."
                ),
                junctions=[corridor.from_junction, through, corridor.to_junction],
                corridors=[corridor.corridor_id, leg_a["corridor_id"], leg_b["corridor_id"]],
            )
        )
        break  # one diversion suggestion at a time; more is noise

    # ── 3. Escalate: held a long time with nobody on it ─────────────────────
    for i in incidents:
        if not i.get("needs_attention"):
            continue
        age = i.get("age_minutes") or 0
        if age < 25:
            continue
        out.append(
            Recommendation(
                kind="ESCALATE",
                urgency="NOW" if i.get("priority") == "P1" else "THIS_SHIFT",
                headline=f"{i['title']} has waited {age:.0f} minutes with no owner",
                detail=(
                    "Nobody has taken responsibility for this since it was raised. Either assign "
                    "it, or record why no action is needed — leaving it open is the one outcome "
                    "that teaches people the board can be ignored."
                ),
                because=[
                    f"Raised at {str(i.get('detected_at', ''))[11:16]}, still unassigned.",
                    i.get("detail", ""),
                ],
                cannot_know="Whether an officer is already dealing with it off-system.",
                junctions=i.get("junctions", []),
                corridors=i.get("corridors", []),
            )
        )

    # ── 4. Nothing to do, said explicitly ──────────────────────────────────
    if not out:
        out.append(
            Recommendation(
                kind="STAND_DOWN",
                urgency="ADVISORY",
                headline="No deployment is indicated",
                detail=(
                    f"{len(corridors)} segments measured, {len(degraded)} above their typical "
                    "travel time, none in a pattern that a posting or a diversion would improve."
                ),
                because=[
                    f"{len(degraded)} segments elevated, none converging on one junction.",
                    "No unowned incident has been waiting more than 25 minutes.",
                ],
                cannot_know=(
                    "Anything off the monitored network. This covers "
                    f"{len(corridors)} segments between {len(network.junctions)} junctions and "
                    "nothing else in the city."
                ),
            )
        )

    order = {"NOW": 0, "THIS_SHIFT": 1, "ADVISORY": 2}
    out.sort(key=lambda r: order[r.urgency])
    return out
